version: '3.8'

services:
  front:
    image: online-chess:latest  # Имя образа вашего Angular приложения
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Пробрасываем порт 80 из контейнера на порт 80 хоста
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro  # Примонтируем конфигурацию Nginx
    restart: unless-stopped  # Автоматический рестарт контейнера в случае падения

networks:
  default:
    driver: bridge
