version: '3.8'

services:
  front:
    image: chess-front:latest
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  back:
    image: chess-server:latest
    build:
      context: back/ChessServer
      dockerfile: Dockerfile
    ports:
      - "7208:443"
      - "5058:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge
