version: '3.8'

services:
  front:
    image: chess-front:latest  # Имя образа вашего Angular приложения
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Пробрасываем порт 80 из контейнера на порт 80 хоста
    restart: unless-stopped  # Автоматический рестарт контейнера в случае падения

networks:
  default:
    driver: bridge
